remote_theme: daattali/beautiful-jekyll


title: Prima tás de bata

author: Joana Wilton

navbar-links:
  Serviços: "/#services"
  Sobre nós: "/#aboutus"
  Contacto: "/contact"

title-img: /assets/img/logo1.png

site-css: "/assets/css/primatasdebata.css"

keywords: "science, communication, education"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "primatasdebata@gmail.com"
  instagram: primatasdebata


url-pretty: "Primatasdebata.com"

footer-img: "/assets/img/footer-bg.png"

gtag: "G-Y80XD5LXBY"

timezone: "Europe/Lisbon"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      nav-short: true
      share-description: "Prima tás de bata | Ciêncie e comunicação"
      share-img: "/assets/img/logo2.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap

